version: "3.4"

services:
    mongo: 
        image: mongo:7.0.9
        restart: always
        ports:
            - 8081:8081
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example